### ISSUE TITLE
Ändern von Einträgen funktioniert nicht richtig

### ISSUE THREAD

**Issue by t-aus-m** [zottelchin/Votierungstracker#12]
Wenn ich einen Eintrag ändere, der nicht der letzte in der Liste ist, dann wird der letzte Eintrag überschrieben. Der Eintrag, der eigentlich bearbeitet werden sollte, wird nicht geändert.

**Comment by zottelchin** [comment]
Das Problem lässt sich bei mir nicht reproduzieren. Kannnst du mir mehr Informationen zum Reproduzieren geben?

**Comment by t-aus-m** [comment]
Interessant. Ich habs gerade nochmal versucht zu reproduzieren, jetzt geht's bei mir auch... 🙈
