### ISSUE TITLE
Eingabevalidierung nicht implementiert

### ISSUE THREAD

**Issue by zottelchin** [zottelchin/Votierungstracker#4]

**Comment by moqmar** [comment]
Sollte mit dem Umbau auf REST (9fb538431879124cdca1fc29d3b27b02f76a468b) erledigt sein - SQL injections sind nicht mehr möglich, ungültige JSON-Angaben werden mit HTTP 400 beantwortet und mit dem Webinterface können keine fehlerhaften Anfragen generiert werden.
